name: Docker Image CI

on:
  push:
    branches: [ "master-1-1" ]  # Trigger only on push events

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Update to v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/rajatroy/demo:${{ github.sha }}  # Build with full image name and tag

      - name: Push the Docker image
        uses: docker/build-push-action@v3  # Use reliable action
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rajatroy/demo:${{ github.sha }}  # Specify full image name and tag
          cache: pull  # Optionally enable cache

      - name: Configure Docker credential helper (optional)  # Address security warning
        run: |
          docker-credential-gcr configure-docker
      
