name: Docker Image CI

on:
  push:
    branches: [ "master-1" ]  # Adjust this branch as needed
  pull_request:
    branches: [ "master-1" ]  # Adjust this branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Replace with v4 for potential improvements
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Optional for more complex builds

      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true  # Only push if build succeeds
          tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}
          cache: pull  # Optionally enable build cache for faster rebuilds

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}

