name: Docker Image CI

on:
  push:
    branches: [ "master-1" ]
  pull_request:
    branches: [ "master-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      with:
          push: true  # Only push if build succeeds
          tags: ${{ secrets.DOCKER_USERNAME }}/test-image:${{ github.sha }}
          cache: pull  # Optionally enable build cache for faster rebuilds

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rajatroy/demo/test-image:${{ github.sha }}  # Include repo name
